package starter.utils.jsons;

public class AuthJson {
    public static String USER_NAME= """
            {
            "username": "%s"
            }
            """;
    public static String USER_PASSWORD = """
                        
             {
                 "password": "%s"
             }
                        
            """;
    public static String ACCESS_TOKEN_DUMMY_DATA="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNzVlOWU2YWYyZTYzZTk3NTc5MjQ0MzIzYjVhNTM1YjU1Y2IwYzFhYThjMzczM2ZiZTc0MjdlNzhjODIyZTI5ZjU0NzVhNjg3NGU5YzI4ZWQxM2ZiYTM2NmM2N2U5NDZlZWExYTg2ZTU2YWQ1ZDA0NTAxMjJlN2I0MmRhMDYzNzAzZDc4ZTczNmNmYTEwYTM2MDA5MTgxYTQ4NzhmMWRkNTQ3MjBiYjBhZjYwYjc5YTk5ZTJkNWUxNTM2OTdhZjM4MWIzMTg5Y2FiMGNlNjg5NDI5OGY5ZmU0M2Y4NjIwYjk2NWI0NWVlN2E5MzcxMzc1YmFhMDVjMTgyYmZhY2NiMTM4YzA1YzdhODM2YWI5MTQ5ZDRkMTkxNGU3MzRmM2NlMDhiMDk4OTM1YTlhYTExMjA3MDQ0ODg4NTQ1NDk3OGUyY2IzZjIwOGUzMGFmNjI2YThiNTRmZDVhNTRmNjVhNzkzOTU4ZjcxZjBhNjMxNDYzMDE4NDA3MDQyZGU2NTEwZWZkODgwNzZmZmQ4NmE2ZThlNGYzMTcxYzMwYzc2YmVjM2JkMmQ2OTA0ZjA3MzAxMTQ5NjFlNmU1NDE2MjE2YWMzNzA3NDkxMDQyMjk0ZGU0ZmQ2NjJjMjQwNzhlMGQ1NzBiOGE5OWEyZDgwZDUwYWNkMTQzNzI0NDZlZDQxNTI3YWE5NjRjZDk0NTJjNjllZDUzOTFhMzEyZDIxZWQyMGIzNDYyMmQ4YjEwMjVlY2E0NzJlNWRiNzMzOTcyNjQ2MDk0M2JjZWM5NDRlMWY2Y2RiYzJkNzcwNzNhMjQzZmUiLCJpYXQiOjE3NDA4MTQ5MDYsImV4cCI6MTc0MDgxODUwNn0.mp1STo5GOuRS0O88pYgvQVXGa-92_5Oeg8YchTfLKiM";
}
